experimentalTernaries: true
printWidth: 80
tabWidth: 4
useTabs: true
singleQuote: true
jsxSingleQuote: true
trailingComma: 'es5'
bracketSpacing: true
bracketSameLine: false
proseWrap: 'always'
plugins:
    [
        'prettier-plugin-svelte',
        'prettier-plugin-tailwindcss',
        '@trivago/prettier-plugin-sort-imports',
    ]
overrides:
    - files: '*.svelte'
      options:
          parser: 'svelte'
